# loading the required libraries
```{r,include=FALSE}
library(knitr)
library(tidyr)
library(dplyr)
library(readr)
library(ggplot2)


# loading the data sets
Amazon_Products <- read.csv("D:/data/amazon_product_data.csv", comment.char="#")
Amazon_Sales <- read.csv("D:/data/amazon_product_sales_data.csv", comment.char="#")
sentiment_data <- read.csv("D:/data/sentimentanalysis.csv", comment.char="#")

```

# Check if the data sets contains any missing observations
```{r}
colSums(is.na(Amazon_Products))
Amazon_Products<-na.omit(Amazon_Products)
colSums(is.na(Amazon_Sales))
colSums(is.na(sentiment_data))
```

```{r}
# products in Amazon
unique(Amazon_Products$Product.name)
amazon_sales_frequency_table <- table(Amazon_Sales$id)
amazon_sales_frequency_df <- as.data.frame(amazon_sales_frequency_table)
head(amazon_sales_frequency_df)
```


###Top 10 Most Expensive Products: Identify the products with the highest New_Price.

```{r}
most_expensive <- Amazon_Products %>%
  arrange(desc(as.numeric(New_Price))) %>%
  head(10)
knitr::kable(most_expensive %>% select(c(Product.name,New_Price))) 

```



### Average Discount Across Products
```{r}

```

